[general]
seedname = "svo"
jobname = "out"
enforce_off_diag = true
block_threshold= 0.001
csc = true

norb_baths = [9]

prec_mu = 0.001

h_int_type = "kanamori"
U = 10.0
J = 1.0

beta = 49
eta = 0.01
n_w = 1000
w_range = [-10, 10]

n_iter_grisb_first = 500
n_iter_grisb_per = 500
n_iter_grisb = 20

dc_type = 1
dc = true
dc_dmft = false

calc_energies = true
grisb_mix = 0.4
grisb_tol = 1e-5

h5_save_freq = 5

[solver]
type = "fci"
num_eig = 1

[dft]
dft_code = "qe"
n_cores = 4
mpi_env = "numa"
projector_type = "w90"
dft_exec = "pw.x"
w90_tolerance = 1e-4
